### ISSUE TITLE
Remove missing file check

### ISSUE THREAD

**Issue by marcobiedermann** [AngeloGulina/gulp-hash-changed#12]
@AngeloGulina What do you think about removing checking for missing hashfile?

If no hashfile is specified, it will fall back to the default option 'fileshashes.json'.
The only question is, if someone does not provide a spring but any other data type, it will throw an error. I think it is obvious to set a string and it is also documented in the readme.

This could clean up the code quite a bit and remove the following lines:
https://github.com/AngeloGulina/gulp-hash-changed/blob/master/index.js#L54-L83

**Comment by AngeloGulina** [comment]
@marcobiedermann I see.

The case I'm covering at the moment (don't know if it makes sense for you, but it is making sense for me) is to avoid to block the pipeline.

For me the case looks like this: we are using _gulp_ to create production assets. Of course, it helps a lot not running the tasks if some of them are already created (please, _note_ the implementation will need to have a properly stream-y approach which I will work on when I have little time). But, if by any chance, someone is wrong on the _hashes_ file, I would not want the build to break so the conditioned task will still run. Hope this is clear how I explained it.

Did you have any specific use case in mind for which the code you linked should be removed?

**Comment by AngeloGulina** [comment]
Hi @marcobiedermann (and happy new year!)

Have you had time to review this question?

Best.

**Comment by marcobiedermann** [comment]
Sorry for replying that late. I think we are talking about two different things.
My point is that I think we do not need to check if `fileshashes.json` is specified (https://github.com/AngeloGulina/gulp-hash-changed/blob/master/index.js#L77) because we fall back to the deaults if not set (https://github.com/AngeloGulina/gulp-hash-changed/blob/master/index.js#L41).
I know this would only remove a few lines and is a minor but I am against every unnecessary code :)

**Comment by AngeloGulina** [comment]
@marcobiedermann let's go w/ this then!

**Comment by AngeloGulina** [comment]
Done :) https://github.com/AngeloGulina/gulp-hash-changed/commit/e7508f75747e21f8b4c2f0dc4451715414ed9eb4
